.ig \"  -*- nroff -*-
Copyright (c) 1999-2010 Philip Hands Computing <http://www.hands.com/>

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.Dd $Mdocdate: June 17 2010 $
.Dt SSH-COPY-ID 1
.Os
.Sh NAME
.Nm ssh-copy-id
.Nd install your public key in a remote machine's authorized_keys
.Sh SYNOPSIS
.Nm ssh-copy-id
.Op Fl i Ar identity_file
.Op Fl p Ar port
.Op Ar user Ns @ Ns
.Ar hostname
.br
.Sh DESCRIPTION
.Nm
is a script that uses
.Xr ssh 1
to log into a remote machine (presumably using a login password, so
password authentication should be enabled, unless you've done some clever
use of multiple identities).  By default it takes the keys listed by
.Ql ssh -l
and endeavours to install them on the remote machine.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl i Ar identity_file
Use the key(s) contained in
.Ar identity_file
rather than looking for identities via
.Xr ssh-add 1
or in the default
.Pa ~/.ssh/id_rsa.pub .
If the filename does not end in
.Pa .pub
this is added. If called with an empty argument (i.e. 
.Ql -i '' ) .
it defaults to using 
.Pa ~/.ssh/id_rsa.pub .
.It Fl p Ar port
Port to connect to on the remote host.
This can be specified on a
per-host basis in
.Xr ssh 1 Ns 's
configuration file.
.El
Default behaviour without
.Fl i ,
is to check if
.Ql ssh-add -L
provides any output, and if so uses that.  Otherwise it falls back to using the contents of 
.Pa ~/.ssh/id_rsa.pub .
Note that this results in the comment on the key being the filename that was given to
.Nm ssh-add
when the key was loaded into your
.Nm ssh-agent
rather than the comment contained in that file, which is a bit of a shame.
.Pp
Once it has one or more fingerprints (by whatever means) it tries to
log in with each key, to see if any of them are already installed
(of course, if you are not using
.Xr ssh-agent 1
this may result in you being prompted for pass-phrases).
It then assembles a list of those that failed to log in, which it then logs in for real, using ssh, and adds the keys to the remote server.
By default it adds the keys by appending them to the remote user's
.Pa ~/.ssh/authorized_keys
(creating the file, and directory, if necessary).  It is also capable of detecting if the remote system is a NetScreen, and using it's 
.Ql set ssh pka-dsa key ...
command instead.
.Pp
.Sh "SEE ALSO"
.Xr ssh 1 ,
.Xr ssh-agent 1 ,
.Xr sshd 8
